name = "AIBECS"
uuid = "ace601d6-714c-11e9-04e5-89b7fad23838"
authors = ["Benoit Pasquier <briochemc@gmail.com>"]
version = "0.7.8"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FieldMetadata = "bf96fef3-21d2-5d20-8afa-0e7d4c32a885"
Flatten = "4c728ea3-d9ee-5c9a-9642-b6f7d7dc04fa"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MetadataArrays = "49441bc9-da82-574f-b07c-a0d10dd4ac13"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
OceanGrids = "cfe838f4-859f-11e9-2ea1-df7d4e7c3537"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Shapefile = "8e980c4a-a4fe-5da2-b3a7-4b4b0353a2f4"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SuiteSparse = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulRecipes = "42071c24-d89e-48dd-8a24-8a12d9b8861f"

[compat]
BSON = "0.2"
DataDeps = "0.7"
DataFrames = "0.20, 0.21"
DiffEqBase = "6"
Distances = "0.9"
Distributions = "0.23"
FieldMetadata = "0.3"
Flatten = "0.3"
ForwardDiff = "0.10"
Interpolations = "0.12"
MetadataArrays = "0.1"
NCDatasets = "0.10"
NearestNeighbors = "0.4"
OceanGrids = "0.3"
RecipesBase = "1"
Reexport = "0.2"
Shapefile = "0.6"
UnPack = "1"
Unitful = "1"
UnitfulRecipes = "0.2"
julia = "1"

[extras]
DualNumbers = "fa6b7ba4-c1ee-5f82-b5fc-ecf0adba8f74"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WorldOceanAtlasTools = "04f20302-f1b9-11e8-29d9-7d841cb0a64a"

[targets]
test = ["Test", "DualNumbers", "WorldOceanAtlasTools", "Plots"]
